import React from "react";
import { format } from "date-fns";

interface CustomerSalesData {
  customerName: string;
  totalSales: number;
  totalItems: number;
  lastOrderDate: string;
}

interface SalesByCustomerPdfContentProps {
  companyName: string;
  companyAddress: string;
  companyContact: string;
  companyLogoUrl?: string;
  reportDate: string;
  customerSales: CustomerSalesData[];
  dateRange?: { from?: Date; to?: Date };
}

const SalesByCustomerPdfContent: React.FC<SalesByCustomerPdfContentProps> = ({
  companyName,
  companyAddress,
  companyContact,
  companyLogoUrl,
  reportDate,
  customerSales,
  dateRange,
}) => {
  const formattedDateRange = dateRange?.from
    ? `${format(dateRange.from, "MMM dd, yyyy")} - ${dateRange.to ? format(dateRange.to, "MMM dd, yyyy") : format(new Date(), "MMM dd, yyyy")}`
    : "All Time";

  const totalOverallSales = customerSales.reduce((sum, data) => sum + data.totalSales, 0);
  const totalOverallItems = customerSales.reduce((sum, data) => sum + data.totalItems, 0);

  return (
    <div className="bg-white text-gray-900 font-sans text-sm p-[20mm]">
      {/* Header */}
      <div className="flex justify-between items-start mb-8">
        <div>
          {companyLogoUrl ? (
            <img src={companyLogoUrl} alt="Company Logo" className="max-h-20 object-contain mb-2" style={{ maxWidth: '1.5in' }} />
          ) : (
            <div className="text-xs text-gray-600 mb-1">YOUR LOGO</div>
          )}
          <h1 className="text-5xl font-extrabold uppercase tracking-tight mb-2">
            SALES BY CUSTOMER
          </h1>
        </div>
        <div className="text-right">
          <p className="text-sm font-semibold">REPORT DATE: {reportDate}</p>
          <p className="text-sm font-semibold">DATA PERIOD: {formattedDateRange}</p>
        </div>
      </div>

      {/* Company Info */}
      <div className="mb-8">
        <p className="font-bold mb-2">REPORT FOR:</p>
        <div className="bg-gray-50 p-3 border border-gray-200 rounded">
          <p className="font-semibold">{companyName}</p>
          <p>{companyContact}</p>
          <p>{companyAddress.split('\n')[0]}</p>
          <p>{companyAddress.split('\n')[1]}</p>
        </div>
      </div>

      {/* Summary Metrics */}
      <div className="grid grid-cols-2 gap-8 mb-8">
        <div>
          <p className="font-bold mb-2">OVERALL SALES SUMMARY:</p>
          <div className="bg-gray-50 p-3 border border-gray-200 rounded space-y-2">
            <div className="flex justify-between">
              <span className="font-semibold">Total Sales Revenue:</span>
              <span>${totalOverallSales.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
            <div className="flex justify-between">
              <span className="font-semibold">Total Items Sold:</span>
              <span>{totalOverallItems.toLocaleString()}</span>
            </div>
            <div className="flex justify-between">
              <span className="font-semibold">Number of Customers:</span>
              <span>{customerSales.length}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Detailed Data Table */}
      <div className="mb-8">
        <p className="font-bold mb-2">DETAILED SALES BY CUSTOMER:</p>
        <table className="w-full border-collapse">
          <thead>
            <tr className="bg-gray-100 border border-gray-300">
              <th className="py-2 px-4 text-left font-semibold border-r border-gray-300">Customer Name</th>
              <th className="py-2 px-4 text-right font-semibold border-r border-gray-300">Total Sales</th>
              <th className="py-2 px-4 text-right font-semibold border-r border-gray-300">Total Items</th>
              <th className="py-2 px-4 text-left font-semibold">Last Order Date</th>
            </tr>
          </thead>
          <tbody>
            {customerSales.length > 0 ? (
              customerSales.map((data, index) => (
                <tr key={index} className="border-b border-gray-200">
                  <td className="py-2 px-4 border-r border-gray-200">{data.customerName}</td>
                  <td className="py-2 px-4 text-right border-r border-gray-200">${data.totalSales.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                  <td className="py-2 px-4 text-right border-r border-gray-200">{data.totalItems.toLocaleString()}</td>
                  <td className="py-2 px-4">{data.lastOrderDate}</td>
                </tr>
              ))
            ) : (
              <tr className="border-b border-gray-200">
                <td colSpan={4} className="py-2 px-4 text-center text-gray-600">No sales data available for this report.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Footer */}
      <div className="text-xs text-gray-500 mt-12 text-right">
        <p>Generated by Fortress on {reportDate}</p>
      </div>
    </div>
  );
};

export default SalesByCustomerPdfContent;